name: contextmenu
description: Display a material context menu using pure Flutter
version: 0.0.1
homepage:

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.0
  after_layout: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
